#!/bin/bash
###############################################################################
# Copyright (C) 2026  Billy Kozak                                             #
#                                                                             #
# This file is part of the jauto-profiler program                             #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU Lesser General Public License as published by #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU Lesser General Public License for more details.                         #
#                                                                             #
# You should have received a copy of the GNU Lesser General Public License    #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
###############################################################################
# Usage: extract-asm <asm-jar> <java-build-dir>
set -e

ASM_JAR="$1"
JAVA_BUILD_DIR="$2"

if [ -n "${JAVA_HOME}" ]; then
	JAR="${JAVA_HOME}/bin/jar"
else
	JAR=jar
fi

ABS_JAR="$(readlink -f "${ASM_JAR}")"
mkdir -p "${JAVA_BUILD_DIR}"
(cd "${JAVA_BUILD_DIR}" && "${JAR}" xf "${ABS_JAR}" org/)
find "${JAVA_BUILD_DIR}/org" -exec touch {} +
