#!/bin/bash
###############################################################################
# Copyright (C) 2026  Billy Kozak                                             #
#                                                                             #
# This file is part of the jauto-profiler program                             #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU Lesser General Public License as published by #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU Lesser General Public License for more details.                         #
#                                                                             #
# You should have received a copy of the GNU Lesser General Public License    #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
###############################################################################
set -e

MUSL_VERSION=1.2.6
MUSL_TARBALL=musl-${MUSL_VERSION}.tar.gz
MUSL_URL=https://musl.libc.org/releases/${MUSL_TARBALL}
EXPECTED_SHA256=d585fd3b613c66151fc3249e8ed44f77020cb5e6c1e635a616d3f9f82460512a

LIBC_DIR=build/libc
TARBALL_PATH=${LIBC_DIR}/${MUSL_TARBALL}
EXTRACT_DIR=${LIBC_DIR}/musl-${MUSL_VERSION}
INSTALL_DIR=$(pwd)/${LIBC_DIR}/musl-install

mkdir -p "${LIBC_DIR}"

if [ ! -f "${TARBALL_PATH}" ]; then
	echo "Downloading musl ${MUSL_VERSION}..."
	curl -fSL -o "${TARBALL_PATH}" "${MUSL_URL}"
fi

ACTUAL_SHA256=$(sha256sum "${TARBALL_PATH}" | awk '{print $1}')
if [ "${ACTUAL_SHA256}" != "${EXPECTED_SHA256}" ]; then
	echo "SHA256 mismatch for ${MUSL_TARBALL}!" >&2
	echo "  expected: ${EXPECTED_SHA256}" >&2
	echo "  actual:   ${ACTUAL_SHA256}" >&2
	rm -f "${TARBALL_PATH}"
	exit 1
fi

if [ ! -d "${EXTRACT_DIR}" ]; then
	echo "Extracting musl ${MUSL_VERSION}..."
	tar -xzf "${TARBALL_PATH}" -C "${LIBC_DIR}"
fi

if [ ! -d "${INSTALL_DIR}" ]; then
	echo "Building musl ${MUSL_VERSION}..."
	NPROC=$(nproc)
	JOBS=$(( NPROC > 1 ? NPROC - 1 : 1 ))
	(
		cd "${EXTRACT_DIR}"
		./configure --prefix="${INSTALL_DIR}" --disable-shared
		make -j"${JOBS}"
		make install
	)
fi
